name: csc522_project
channels:
- spacy
- defaults
dependencies:
- certifi=2016.2.28=py36_0
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.6.2=0
- readline=6.2=2
- setuptools=36.4.0=py36_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - alembic==0.9.6
  - appnope==0.1.0
  - banal==0.2.0
  - bleach==2.1.1
  - chardet==3.0.4
  - cycler==0.10.0
  - cymem==1.31.2
  - cytoolz==0.8.2
  - dataset==1.0.2
  - decorator==4.1.2
  - dill==0.2.7.1
  - entrypoints==0.2.3
  - ftfy==4.4.3
  - html5lib==1.0b10
  - idna==2.6
  - ipykernel==4.6.1
  - ipython==6.2.1
  - ipython-genutils==0.2.0
  - ipywidgets==7.0.3
  - jedi==0.11.0
  - jinja2==2.9.6
  - jsonschema==2.6.0
  - jupyter==1.0.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.3.0
  - mako==1.0.7
  - markupsafe==1.0
  - matplotlib==2.1.0
  - mistune==0.7.4
  - murmurhash==0.26.4
  - nbconvert==5.3.1
  - nbformat==4.4.0
  - normality==0.5.0
  - notebook==5.2.0
  - numpy==1.13.3
  - pandas==0.20.3
  - pandocfilters==1.4.2
  - parso==0.1.0
  - pathlib==1.0.1
  - pexpect==4.2.1
  - pickleshare==0.7.4
  - plac==0.9.6
  - preshed==1.0.0
  - prompt-toolkit==1.0.15
  - psycopg2==2.7.3.1
  - ptyprocess==0.5.2
  - pydotplus==2.0.2
  - pygments==2.2.0
  - pyparsing==2.2.0
  - python-dateutil==2.6.1
  - python-editor==1.0.3
  - pytz==2017.2
  - pyzmq==16.0.2
  - qtconsole==4.3.1
  - regex==2017.9.23
  - requests==2.18.4
  - scikit-learn==0.19.1
  - scipy==0.19.1
  - simplegeneric==0.8.1
  - six==1.11.0
  - spacy==1.9.0
  - sqlalchemy==1.1.14
  - termcolor==1.1.0
  - terminado==0.6
  - testpath==0.3.1
  - thinc==6.5.2
  - toolz==0.8.2
  - tornado==4.5.2
  - tqdm==4.19.4
  - traitlets==4.3.2
  - ujson==1.35
  - urllib3==1.22
  - wcwidth==0.1.7
  - webencodings==0.5.1
  - widgetsnbextension==3.0.6
  - wrapt==1.10.11

